-- ============================================================
-- SEED: Countries (comprehensive global list)
-- ============================================================
INSERT INTO countries (iso_code, name, flag, region, sub_region) VALUES
-- Europe
('AL','Albania','🇦🇱','Europe','Southern Europe'),
('AD','Andorra','🇦🇩','Europe','Southern Europe'),
('AT','Austria','🇦🇹','Europe','Western Europe'),
('BY','Belarus','🇧🇾','Europe','Eastern Europe'),
('BE','Belgium','🇧🇪','Europe','Western Europe'),
('BA','Bosnia and Herzegovina','🇧🇦','Europe','Southern Europe'),
('BG','Bulgaria','🇧🇬','Europe','Eastern Europe'),
('HR','Croatia','🇭🇷','Europe','Southern Europe'),
('CY','Cyprus','🇨🇾','Europe','Southern Europe'),
('CZ','Czech Republic','🇨🇿','Europe','Eastern Europe'),
('DK','Denmark','🇩🇰','Europe','Northern Europe'),
('EE','Estonia','🇪🇪','Europe','Northern Europe'),
('FI','Finland','🇫🇮','Europe','Northern Europe'),
('FR','France','🇫🇷','Europe','Western Europe'),
('DE','Germany','🇩🇪','Europe','Western Europe'),
('GR','Greece','🇬🇷','Europe','Southern Europe'),
('HU','Hungary','🇭🇺','Europe','Eastern Europe'),
('IS','Iceland','🇮🇸','Europe','Northern Europe'),
('IE','Ireland','🇮🇪','Europe','Northern Europe'),
('IT','Italy','🇮🇹','Europe','Southern Europe'),
('XK','Kosovo','🇽🇰','Europe','Southern Europe'),
('LV','Latvia','🇱🇻','Europe','Northern Europe'),
('LI','Liechtenstein','🇱🇮','Europe','Western Europe'),
('LT','Lithuania','🇱🇹','Europe','Northern Europe'),
('LU','Luxembourg','🇱🇺','Europe','Western Europe'),
('MT','Malta','🇲🇹','Europe','Southern Europe'),
('MD','Moldova','🇲🇩','Europe','Eastern Europe'),
('MC','Monaco','🇲🇨','Europe','Western Europe'),
('ME','Montenegro','🇲🇪','Europe','Southern Europe'),
('NL','Netherlands','🇳🇱','Europe','Western Europe'),
('MK','North Macedonia','🇲🇰','Europe','Southern Europe'),
('NO','Norway','🇳🇴','Europe','Northern Europe'),
('PL','Poland','🇵🇱','Europe','Eastern Europe'),
('PT','Portugal','🇵🇹','Europe','Southern Europe'),
('RO','Romania','🇷🇴','Europe','Eastern Europe'),
('RU','Russia','🇷🇺','Europe','Eastern Europe'),
('SM','San Marino','🇸🇲','Europe','Southern Europe'),
('RS','Serbia','🇷🇸','Europe','Southern Europe'),
('SK','Slovakia','🇸🇰','Europe','Eastern Europe'),
('SI','Slovenia','🇸🇮','Europe','Southern Europe'),
('ES','Spain','🇪🇸','Europe','Southern Europe'),
('SE','Sweden','🇸🇪','Europe','Northern Europe'),
('CH','Switzerland','🇨🇭','Europe','Western Europe'),
('TR','Turkey','🇹🇷','Europe','Western Asia'),
('UA','Ukraine','🇺🇦','Europe','Eastern Europe'),
('GB','United Kingdom','🇬🇧','Europe','Northern Europe'),
('VA','Vatican City','🇻🇦','Europe','Southern Europe'),
-- Asia & Middle East
('AF','Afghanistan','🇦🇫','Asia','Southern Asia'),
('AM','Armenia','🇦🇲','Asia','Western Asia'),
('AZ','Azerbaijan','🇦🇿','Asia','Western Asia'),
('BH','Bahrain','🇧🇭','Asia','Western Asia'),
('BD','Bangladesh','🇧🇩','Asia','Southern Asia'),
('BT','Bhutan','🇧🇹','Asia','Southern Asia'),
('BN','Brunei','🇧🇳','Asia','South-Eastern Asia'),
('KH','Cambodia','🇰🇭','Asia','South-Eastern Asia'),
('CN','China','🇨🇳','Asia','Eastern Asia'),
('GE','Georgia','🇬🇪','Asia','Western Asia'),
('IN','India','🇮🇳','Asia','Southern Asia'),
('ID','Indonesia','🇮🇩','Asia','South-Eastern Asia'),
('IR','Iran','🇮🇷','Asia','Southern Asia'),
('IQ','Iraq','🇮🇶','Asia','Western Asia'),
('IL','Israel','🇮🇱','Asia','Western Asia'),
('JP','Japan','🇯🇵','Asia','Eastern Asia'),
('JO','Jordan','🇯🇴','Asia','Western Asia'),
('KZ','Kazakhstan','🇰🇿','Asia','Central Asia'),
('KW','Kuwait','🇰🇼','Asia','Western Asia'),
('KG','Kyrgyzstan','🇰🇬','Asia','Central Asia'),
('LA','Laos','🇱🇦','Asia','South-Eastern Asia'),
('LB','Lebanon','🇱🇧','Asia','Western Asia'),
('MY','Malaysia','🇲🇾','Asia','South-Eastern Asia'),
('MV','Maldives','🇲🇻','Asia','Southern Asia'),
('MN','Mongolia','🇲🇳','Asia','Eastern Asia'),
('MM','Myanmar','🇲🇲','Asia','South-Eastern Asia'),
('NP','Nepal','🇳🇵','Asia','Southern Asia'),
('KP','North Korea','🇰🇵','Asia','Eastern Asia'),
('OM','Oman','🇴🇲','Asia','Western Asia'),
('PK','Pakistan','🇵🇰','Asia','Southern Asia'),
('PS','Palestine','🇵🇸','Asia','Western Asia'),
('PH','Philippines','🇵🇭','Asia','South-Eastern Asia'),
('QA','Qatar','🇶🇦','Asia','Western Asia'),
('SA','Saudi Arabia','🇸🇦','Asia','Western Asia'),
('SG','Singapore','🇸🇬','Asia','South-Eastern Asia'),
('KR','South Korea','🇰🇷','Asia','Eastern Asia'),
('LK','Sri Lanka','🇱🇰','Asia','Southern Asia'),
('SY','Syria','🇸🇾','Asia','Western Asia'),
('TJ','Tajikistan','🇹🇯','Asia','Central Asia'),
('TH','Thailand','🇹🇭','Asia','South-Eastern Asia'),
('TL','Timor-Leste','🇹🇱','Asia','South-Eastern Asia'),
('TM','Turkmenistan','🇹🇲','Asia','Central Asia'),
('AE','United Arab Emirates','🇦🇪','Asia','Western Asia'),
('UZ','Uzbekistan','🇺🇿','Asia','Central Asia'),
('VN','Vietnam','🇻🇳','Asia','South-Eastern Asia'),
('YE','Yemen','🇾🇪','Asia','Western Asia'),
-- Africa
('DZ','Algeria','🇩🇿','Africa','Northern Africa'),
('AO','Angola','🇦🇴','Africa','Middle Africa'),
('BJ','Benin','🇧🇯','Africa','Western Africa'),
('BW','Botswana','🇧🇼','Africa','Southern Africa'),
('BF','Burkina Faso','🇧🇫','Africa','Western Africa'),
('BI','Burundi','🇧🇮','Africa','Eastern Africa'),
('CM','Cameroon','🇨🇲','Africa','Middle Africa'),
('CV','Cabo Verde','🇨🇻','Africa','Western Africa'),
('CF','Central African Republic','🇨🇫','Africa','Middle Africa'),
('TD','Chad','🇹🇩','Africa','Middle Africa'),
('KM','Comoros','🇰🇲','Africa','Eastern Africa'),
('CG','Congo','🇨🇬','Africa','Middle Africa'),
('CD','DR Congo','🇨🇩','Africa','Middle Africa'),
('CI','Côte d''Ivoire','🇨🇮','Africa','Western Africa'),
('DJ','Djibouti','🇩🇯','Africa','Eastern Africa'),
('EG','Egypt','🇪🇬','Africa','Northern Africa'),
('GQ','Equatorial Guinea','🇬🇶','Africa','Middle Africa'),
('ER','Eritrea','🇪🇷','Africa','Eastern Africa'),
('ET','Ethiopia','🇪🇹','Africa','Eastern Africa'),
('GA','Gabon','🇬🇦','Africa','Middle Africa'),
('GM','Gambia','🇬🇲','Africa','Western Africa'),
('GH','Ghana','🇬🇭','Africa','Western Africa'),
('GN','Guinea','🇬🇳','Africa','Western Africa'),
('GW','Guinea-Bissau','🇬🇼','Africa','Western Africa'),
('KE','Kenya','🇰🇪','Africa','Eastern Africa'),
('LS','Lesotho','🇱🇸','Africa','Southern Africa'),
('LR','Liberia','🇱🇷','Africa','Western Africa'),
('LY','Libya','🇱🇾','Africa','Northern Africa'),
('MG','Madagascar','🇲🇬','Africa','Eastern Africa'),
('MW','Malawi','🇲🇼','Africa','Eastern Africa'),
('ML','Mali','🇲🇱','Africa','Western Africa'),
('MR','Mauritania','🇲🇷','Africa','Western Africa'),
('MU','Mauritius','🇲🇺','Africa','Eastern Africa'),
('MA','Morocco','🇲🇦','Africa','Northern Africa'),
('MZ','Mozambique','🇲🇿','Africa','Eastern Africa'),
('NA','Namibia','🇳🇦','Africa','Southern Africa'),
('NE','Niger','🇳🇪','Africa','Western Africa'),
('NG','Nigeria','🇳🇬','Africa','Western Africa'),
('RW','Rwanda','🇷🇼','Africa','Eastern Africa'),
('ST','Sao Tome and Principe','🇸🇹','Africa','Middle Africa'),
('SN','Senegal','🇸🇳','Africa','Western Africa'),
('SL','Sierra Leone','🇸🇱','Africa','Western Africa'),
('SO','Somalia','🇸🇴','Africa','Eastern Africa'),
('ZA','South Africa','🇿🇦','Africa','Southern Africa'),
('SS','South Sudan','🇸🇸','Africa','Eastern Africa'),
('SD','Sudan','🇸🇩','Africa','Northern Africa'),
('SZ','Eswatini','🇸🇿','Africa','Southern Africa'),
('TZ','Tanzania','🇹🇿','Africa','Eastern Africa'),
('TG','Togo','🇹🇬','Africa','Western Africa'),
('TN','Tunisia','🇹🇳','Africa','Northern Africa'),
('UG','Uganda','🇺🇬','Africa','Eastern Africa'),
('ZM','Zambia','🇿🇲','Africa','Eastern Africa'),
('ZW','Zimbabwe','🇿🇼','Africa','Southern Africa'),
-- Americas
('AG','Antigua and Barbuda','🇦🇬','Americas','Caribbean'),
('AR','Argentina','🇦🇷','Americas','South America'),
('BS','Bahamas','🇧🇸','Americas','Caribbean'),
('BB','Barbados','🇧🇧','Americas','Caribbean'),
('BZ','Belize','🇧🇿','Americas','Central America'),
('BO','Bolivia','🇧🇴','Americas','South America'),
('BR','Brazil','🇧🇷','Americas','South America'),
('CA','Canada','🇨🇦','Americas','Northern America'),
('CL','Chile','🇨🇱','Americas','South America'),
('CO','Colombia','🇨🇴','Americas','South America'),
('CR','Costa Rica','🇨🇷','Americas','Central America'),
('CU','Cuba','🇨🇺','Americas','Caribbean'),
('DM','Dominica','🇩🇲','Americas','Caribbean'),
('DO','Dominican Republic','🇩🇴','Americas','Caribbean'),
('EC','Ecuador','🇪🇨','Americas','South America'),
('SV','El Salvador','🇸🇻','Americas','Central America'),
('GD','Grenada','🇬🇩','Americas','Caribbean'),
('GT','Guatemala','🇬🇹','Americas','Central America'),
('GY','Guyana','🇬🇾','Americas','South America'),
('HT','Haiti','🇭🇹','Americas','Caribbean'),
('HN','Honduras','🇭🇳','Americas','Central America'),
('JM','Jamaica','🇯🇲','Americas','Caribbean'),
('MX','Mexico','🇲🇽','Americas','Central America'),
('NI','Nicaragua','🇳🇮','Americas','Central America'),
('PA','Panama','🇵🇦','Americas','Central America'),
('PY','Paraguay','🇵🇾','Americas','South America'),
('PE','Peru','🇵🇪','Americas','South America'),
('KN','Saint Kitts and Nevis','🇰🇳','Americas','Caribbean'),
('LC','Saint Lucia','🇱🇨','Americas','Caribbean'),
('VC','Saint Vincent and the Grenadines','🇻🇨','Americas','Caribbean'),
('SR','Suriname','🇸🇷','Americas','South America'),
('TT','Trinidad and Tobago','🇹🇹','Americas','Caribbean'),
('US','United States','🇺🇸','Americas','Northern America'),
('UY','Uruguay','🇺🇾','Americas','South America'),
('VE','Venezuela','🇻🇪','Americas','South America'),
-- Oceania
('AU','Australia','🇦🇺','Oceania','Australia and New Zealand'),
('FJ','Fiji','🇫🇯','Oceania','Melanesia'),
('KI','Kiribati','🇰🇮','Oceania','Micronesia'),
('MH','Marshall Islands','🇲🇭','Oceania','Micronesia'),
('FM','Micronesia','🇫🇲','Oceania','Micronesia'),
('NR','Nauru','🇳🇷','Oceania','Micronesia'),
('NZ','New Zealand','🇳🇿','Oceania','Australia and New Zealand'),
('PW','Palau','🇵🇼','Oceania','Micronesia'),
('PG','Papua New Guinea','🇵🇬','Oceania','Melanesia'),
('WS','Samoa','🇼🇸','Oceania','Polynesia'),
('SB','Solomon Islands','🇸🇧','Oceania','Melanesia'),
('TO','Tonga','🇹🇴','Oceania','Polynesia'),
('TV','Tuvalu','🇹🇻','Oceania','Polynesia'),
('VU','Vanuatu','🇻🇺','Oceania','Melanesia')
ON CONFLICT (iso_code) DO NOTHING;
